did a few changes in the flow

diff --git a/.github/workflows/konnect-gateway-deployment.yml b/.github/workflows/konnect-gateway-deployment.yml
--- a/.github/workflows/konnect-gateway-deployment.yml
+++ b/.github/workflows/konnect-gateway-deployment.yml
@@ -34,6 +34,7 @@ jobs:
       - name: Lint OAS spec using Spectral
         run: spectral lint ./kong-config/spec.yaml --ruleset ./kong-config/.spectral.yaml
 
+
       - name: Generate new gateway configuration
         run: |
           deck file openapi2kong --spec ./kong-config/spec.yaml --select-tag=hello,dev --output-file kong.yaml
@@ -65,6 +66,7 @@ jobs:
           KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
           CP_NAME: ${{ secrets.CP_NAME }}
 
+
       - name: Run API Tests
         id: apiTests
         run: newman run newman/newman_collection.postman_collection.json
@@ -91,7 +93,21 @@ jobs:
           echo "CONTROL_PLANE_NAME: ${{ vars.CONTROL_PLANE_NAME }}"
           echo "GATEWAY_SERVICE_NAME: ${{ vars.GATEWAY_SERVICE_NAME }}"
 
-      
+      - name: Check API Product is already exist or not or Creating new API product
+        run: |
+          api_product_name="${{ vars.API_PRODUCT_NAME }}"
+
+          api_product_id=$(curl --request GET \
+            --url ${{ vars.ADMIN_API_URL }}/api-products \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+            | jq -r --arg api_product_name "$api_product_name" '.data[] | select(.name == $api_product_name) | .id // empty')
+
+          if [ "$api_product_id" = "empty" ]; then
+            echo "Error: API Product ID not found."
+            exit 1
+          fi
+
+          echo "API_PRODUCT_ID=$api_product_id" >> $GITHUB_ENV
 
 
       - name: Get API product ID
@@ -101,7 +117,7 @@ jobs:
           api_product_id=$(curl --request GET \
             --url ${{ vars.ADMIN_API_URL }}/api-products \
             --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
-            | jq -r --arg api_product_name "$api_product_name" '.data[] | select(.name == $api_product_name) | .id // empty')
+            | jq -r --arg api_product_name "tase-product" '.data[] | select(.name == $api_product_name) | .id // empty')
 
           if [ "$api_product_id" = "empty" ]; then
             echo "Error: API Product ID not found."
