Update konnect-gateway-deployment.yml

diff --git a/.github/workflows/konnect-gateway-deployment.yml b/.github/workflows/konnect-gateway-deployment.yml
--- a/.github/workflows/konnect-gateway-deployment.yml
+++ b/.github/workflows/konnect-gateway-deployment.yml
@@ -101,23 +101,59 @@ jobs:
       #     KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
       #     CONTROL_PLANE_NAME: ${{ env.CONTROL_PLANE_NAME }}
 
-  publish-customer-api-to-portal:
-    name: Publish OAS to dev portal
-    # needs: deploy_to_konnect
+  name: konnect-gateway-deployment
+
+on:
+  push:
+    branches:
+      - main
+  workflow_dispatch:
+
+jobs:
+  deploy_to_konnect:
     runs-on: ubuntu-latest
+    name: Deploying Kong Configuration
     steps:
       - name: Checkout Code
         uses: actions/checkout@v2
 
-      - name: Find OAS file name in the directory
+      - name: Print current working directory
+        run: pwd
+
+      - name: Verify file path
+        run: ls -al ./testing/kong-config/spec.yaml
+
+      - name: Install Node.js and npm
+        uses: actions/setup-node@v2
+        with:
+          node-version: '16'
+
+      - name: Install Newman
+        run: npm install -g newman
+
+      - name: Install Spectral
+        run: npm install -g @stoplight/spectral-cli
+
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
+
+      - name: Install yq
+        run: sudo apt-get install -y python3-pip && pip3 install yq
+
+      - name: Change directory to kong-config and check spec.yaml
         run: |
-          cd ./kong-config
-          SPEC_FILE="spec.yaml"  # Assuming the file name is known
+          cd testing/kong-config
+          if [ ! -f spec.yaml ]; then
+            echo "spec.yaml file not found in ./testing/kong-config directory"
+            exit 1
+          fi
+          SPEC_FILE="spec.yaml"
           echo "SPEC_FILE=$SPEC_FILE" >> $GITHUB_ENV
-          
+
       - name: Fetch environment variables and extract Product details
         id: set_env_vars
         run: |
+          cd testing/kong-config
           echo "API_PRODUCT_NAME=$(yq e '.info.title' $SPEC_FILE | sed 's/ /-/g')" >> $GITHUB_ENV
           echo "API_PRODUCT_DESCRIPTION=$(yq e '.info.description' $SPEC_FILE)" >> $GITHUB_ENV
           echo "API_PRODUCT_VERSION=$(yq e '.info.version' $SPEC_FILE)" >> $GITHUB_ENV
@@ -127,7 +163,7 @@ jobs:
           echo "CONTROL_PLANE_NAME=$CONTROL_PLANE_NAME" >> $GITHUB_ENV
           echo "APPLICATION_AUTH_STRATEGY=$APPLICATION_AUTH_STRATEGY" >> $GITHUB_ENV
           echo "API_PRODUCT_ALREADY_EXISTS=false" >> $GITHUB_ENV
-          
+
       - name: Debug API_PRODUCT_NAME and other variables
         run: |
           echo "API_PRODUCT_NAME=${{ env.API_PRODUCT_NAME }}"
@@ -230,63 +266,5 @@ jobs:
       - name: Retrieving current service link information to the api product
         run: |
           # Retrieving information on which API product version is associated with a service link in case of a rollback.
-          rollback_api_product_version=$(curl -s --location --request GET "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions" \
-            --header "Authorization: ${{ secrets.KONNECT_TOKEN }}" \
-            | jq -r '.data[] | select(.gateway_service != null) | .name')
-          rollback_api_product_version_id=$(curl -s --location --request GET "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions" \
-            --header "Authorization: ${{ secrets.KONNECT_TOKEN }}" \
-            | jq -r '.data[] | select(.gateway_service != null) | .id')
-          echo "ROLLBACK_SERVICE_LINK_VERSION=$rollback_api_product_version" >> $GITHUB_ENV
-          echo "ROLLBACK_SERVICE_LINK_VERSION_ID=$rollback_api_product_version_id" >> $GITHUB_ENV
-
-      - name: Link service to the product version
-        run: |
-          echo "Check if current service link product version and the version specified in the OAS specification version is same or not.."
-          if [[ "${{ env.ROLLBACK_SERVICE_LINK_VERSION }}" != "${{ env.API_PRODUCT_VERSION }}" ]]; then
-            echo "The product version differs; therefore, unlinking the service from ${{ env.ROLLBACK_SERVICE_LINK_VERSION }}"
-            curl --location --request DELETE "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$ROLLBACK_SERVICE_LINK_VERSION_ID" \
-              --header "Authorization: ${{ secrets.KONNECT_TOKEN }}" \
-              --header 'Content-Type: application/json'
-            echo "Linking the service to ${{ env.API_PRODUCT_VERSION }}"
-            curl --location --request PATCH "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_PRODUCT_VERSION_ID" \
-              --header "Authorization: ${{ secrets.KONNECT_TOKEN }}" \
-              --header 'Content-Type: application/json' \
-              --data '{
-                "name": "${{ env.API_PRODUCT_VERSION }}",
-                "publish_status": "published",
-                "deprecated": false,
-                "notify": true,
-                "gateway_service": {
-                  "control_plane_id": "${{ env.CONTROL_PLANE_ID }}",
-                  "id": "${{ env.SERVICE_ID }}"
-                }
-              }'
-          else
-            echo "The product versions match (current - ${{ env.ROLLBACK_SERVICE_LINK_VERSION }} & OAS Spec - ${{ env.API_PRODUCT_VERSION }}); therefore, no changes needed for the service link"
-          fi
-
-      - name: Upload spec on the version
-        run: |
-          encoded_spec=$(base64 -w 0 ./kong-config/${{ env.SPEC_FILE }})
-          echo "Check if specifications is already there or not .."
-          specifications_id=$(curl --location --request GET "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_PRODUCT_VERSION_ID/specifications" \
-            --header "Authorization: ${{ secrets.KONNECT_TOKEN }}" \
-            | jq -r '.data[] | .id')
-          if [ -n "$specifications_id" ]; then
-            echo "Specifications ID: $specifications_id"
-            curl --location --request PATCH "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_PRODUCT_VERSION_ID/specifications/$specifications_id" \
-              --header "Authorization: ${{ secrets.KONNECT_TOKEN }}" \
-              --header 'Content-Type: application/json' \
-              --data '{
-                "name": "${{ env.SPEC_FILE }}",
-                "content": "'"$encoded_spec"'"
-              }'
-          else
-            curl --location --request POST "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_PRODUCT_VERSION_ID/specifications" \
-              --header "Authorization: ${{ secrets.KONNECT_TOKEN }}" \
-              --header 'Content-Type: application/json' \
-              --data '{
-                "name": "${{ env.SPEC_FILE }}",
-                "content": "'"$encoded_spec"'"
-              }'
-          fi
+          rollback_api_product_version=$(curl -s --location --request GET "${{ vars.ADMIN_API_URL }}/api-products/${{ env.API_PRODUCT_ID }}/service-links")
+          echo "ROLLBACK_API_PRODUCT_VERSION=$rollback_api_product_version" >> $GITHUB_ENV
