did a few changes in the flow

diff --git a/.github/workflows/konnect-gateway-deployment.yml b/.github/workflows/konnect-gateway-deployment.yml
--- a/.github/workflows/konnect-gateway-deployment.yml
+++ b/.github/workflows/konnect-gateway-deployment.yml
@@ -239,21 +239,22 @@ jobs:
 
       - name: Enabling Auth Strategy
         if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
-        id: FinalTest
         run: |
-          curl --location --request PATCH "${{ secrets.ADMIN_API_URL }}/portals/$DEV_PORTAL_ID/product-versions/$API_Product_Version_ID" \
+          response=$(curl -s -o /dev/null -w "%{http_code}" --location --request PATCH "${{ secrets.ADMIN_API_URL }}/portals/$DEV_PORTAL_ID/product-versions/$API_Product_Version_ID" \
             --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
             --header 'Content-Type: application/json' \
             --data '{
                 "application_registration_enabled": true,
                 "auth_strategy_ids": [
-                  "${{ env.Auth_Strategy_I }}"
+                  "${{ env.Auth_Strategy_ID }}"
                 ],
                 "auto_approve_registration": true
-              }'
-      - name: Back out changes on failure
-        if: always() && steps.FinalTest.outcome == 'failure'
-        run: |
-          curl --request DELETE \
-            --url ${{ secrets.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID \
-            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}'
+              }')
+
+          if [ $response -ne 201 ]; then
+            echo "Failed to enable Auth Strategy. Deleting the API product version..."
+            curl --request DELETE \
+              --url ${{ secrets.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID \
+              --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}'
+            exit 1
+          fi
