did a few changes in the flow

diff --git a/.github/workflows/konnect-gateway-deployment.yml b/.github/workflows/konnect-gateway-deployment.yml
--- a/.github/workflows/konnect-gateway-deployment.yml
+++ b/.github/workflows/konnect-gateway-deployment.yml
@@ -228,26 +228,24 @@ jobs:
                   }'
 
       - name: Enabling Auth Strategy
-  if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
-  run: |
-    response=$(curl -s -w "%{http_code}" --location --request PATCH "${{ secrets.ADMIN_API_URL }}/portals/$DEV_PORTAL_ID/product-versions/$API_Product_Version_ID" \
-      --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
-      --header 'Content-Type: application/json' \
-      --data '{
-        "application_registration_enabled": true,
-        "auth_strategy_ids": [
-          "${{ env.Auth_Strategy_I }}"
-        ],
-        "auto_approve_registration": true
-      }')
+        if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
+        run: |
+          response=$(curl -s -o /dev/null -w "%{http_code}" --location --request PATCH "${{ secrets.ADMIN_API_URL }}/portals/$DEV_PORTAL_ID/product-versions/$API_Product_Version_ID" \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+            --header 'Content-Type: application/json' \
+            --data '{
+               "application_registration_enabled": true,
+              "auth_strategy_ids": [
+                "${{ env.Auth_Strategy_I }}"
+              ],
+              "auto_approve_registration": true
+            }')
 
-    if [ "$response" -eq 200 ]; then
-      echo "Success! Auth Strategy enabled."
-    else
-      echo "Failed to enable Auth Strategy. Deleting the API product version..."
-      curl --request DELETE \
-        --url "${{ secrets.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID" \
-        --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}'
-      exit 1
-    fi
+          if [ "$response" != "200" ]; then
+            echo "Failed to enable Auth Strategy. Deleting the API product version..."
+            curl --request DELETE \
+              --url "${{ secrets.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID" \
+              --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}'
+            exit 1
+          fi
 
