Update konnect-gatewat-deployment.yml

diff --git a/.github/workflows/konnect-gatewat-deployment.yml b/.github/workflows/konnect-gatewat-deployment.yml
--- a/.github/workflows/konnect-gatewat-deployment.yml
+++ b/.github/workflows/konnect-gatewat-deployment.yml
@@ -1,7 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
 name: konnect-gatewat-deployment
-
 on:
   push:
     branches: [ "main" ]
@@ -76,4 +75,142 @@ jobs:
           KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
           CP_NAME: ${{ secrets.CP_NAME }}
 
-          
+  publish-customer-api-to-portal:
+    name: Publish OAS to dev portal
+    needs: deploy_to_konnect
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v2
+
+      - name: Featch environment variables
+        id: set_env_vars
+        run: |
+          echo "API_PRODUCT_NAME: ${{ vars.API_PRODUCT_NAME }}"
+          echo "CONTROL_PLANE_NAME: ${{ vars.CONTROL_PLANE_NAME }}" 
+          echo "GATEWAY_SERVICE_NAME: ${{ vars.GATEWAY_SERVICE_NAME }}" 
+
+      - name: Create API product
+        run: |
+          curl --request POST \
+            --url ${{ vars.ADMIN_API_URL }}/api-products \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+            --header 'Content-Type: application/json' \
+            --data '{
+              "name": "${{ vars.API_PRODUCT_NAME }}",
+              "description": "Creating through admin api",
+              "labels": {}
+            }' 
+
+      - name: Get API product ID
+        run: >
+          api_product_name="${{ vars.API_PRODUCT_NAME }}"
+
+          api_product_id=$(curl --request GET \
+            --url ${{ vars.ADMIN_API_URL }}/api-products \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+            | jq -r --arg api_product_name "$api_product_name" '.data[] | select(.name == $api_product_name) | .id // empty')
+
+          if [ "$api_product_id" = "empty" ]; then
+            echo "Error: API Product ID not found."
+            exit 1
+          fi
+
+          echo "API_PRODUCT_ID=$api_product_id" >> $GITHUB_ENV 
+
+      - name: Get Dev Portal ID
+        run: |
+          Dev_portal_id=$(curl --request GET \
+            --url ${{ vars.ADMIN_API_URL }}/portals \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+            | jq -r '.data[].id')
+              echo "DEV_PORTAL_ID=$Dev_portal_id" >> $GITHUB_ENV
+
+      - name: Publish product to the dev portal
+        run: |
+          echo "API Product ID: $API_PRODUCT_ID"
+          echo "Dev Portal ID: $DEV_PORTAL_ID"
+          curl --request PATCH \
+           --url ${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID \
+           --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+           --header 'Content-Type: application/json' \
+           --data "{
+             \"portal_ids\":[\"$DEV_PORTAL_ID\"]
+           }"
+
+      - name: Create the product version
+        run: >
+          echo "API Product ID: $API_PRODUCT_ID"
+
+          api_product_version_id=$(curl --request POST \
+            --url ${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+            --header 'Content-Type: application/json' \
+            --data '{
+              "name": "v1",
+              "publish_status": "published",
+              "gateway_service": null
+            }'| jq -r '.id')
+              echo "API_Product_Version_ID=$api_product_version_id" >> $GITHUB_ENV
+              echo "API Product Version ID: $API_Product_Version_ID"
+
+      - name: Get Control Plane ID
+        run: >
+          control_plane_name="${{ vars.CONTROL_PLANE_NAME }}"
+
+          control_plane_id=$(curl --location '${{ vars.ADMIN_API_URL }}/control-planes' \
+
+          --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+
+          | jq -r --arg control_plane_name "$control_plane_name" '.data[] | select(.name == $control_plane_name) | .id')
+
+          echo "Control_Plane_ID=$control_plane_id" >> $GITHUB_ENV
+
+      - name: Get Service ID
+        run: >
+          echo "Control Plane Id: $Control_Plane_ID"
+
+          gateway_service_name="${{ vars.GATEWAY_SERVICE_NAME }}"
+
+          service_id=$(curl --location "${{ vars.ADMIN_API_URL }}/control-planes/$Control_Plane_ID/core-entities/services" \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+            | jq -r --arg gateway_service_name "$gateway_service_name" '.data[] | select(.name == $gateway_service_name) | .id')
+          echo "Service_ID=$service_id" >> $GITHUB_ENV
+
+      - name: Link service to the product version
+        run: >
+          echo "API PRODUCT ID: $API_PRODUCT_ID"
+
+          echo "Control Plane ID: $Control_Plane_ID"
+
+          echo "Service ID: $Service_ID"
+
+          echo "API Product Version ID: $API_Product_Version_ID"
+
+          curl --location --request PATCH "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID" \
+                --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+                --header 'Content-Type: application/json' \
+                --data "{
+                        \"name\": \"v1\",
+                        \"publish_status\": \"published\",
+                        \"deprecated\": false,
+                        \"notify\": true,
+                        \"gateway_service\": {
+                        \"control_plane_id\": \"$Control_Plane_ID\",
+                        \"id\": \"$Service_ID\"
+                                }
+                       }"
+
+      - name: Upload spec on the version
+        run: |
+          echo "API PRODUCT ID: $API_PRODUCT_ID"
+          echo "API Product Version ID: $API_Product_Version_ID"
+          encoded_spec=$(base64 -w 0 ./kong-config/spec.yaml)
+          echo $encoded_spec
+          curl --location --request POST "${{ vars.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID/specifications" \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+            --header 'Content-Type: application/json' \
+            --data '{
+                    "name": "spec.yaml",
+                    "content": "'"$encoded_spec"'"
+                  }'
