did a few changes in the flow

diff --git a/.github/workflows/konnect-gateway-deployment.yml b/.github/workflows/konnect-gateway-deployment.yml
--- a/.github/workflows/konnect-gateway-deployment.yml
+++ b/.github/workflows/konnect-gateway-deployment.yml
@@ -237,31 +237,10 @@ jobs:
             | jq -r --arg auth_strategy_name "$auth_strategy_name" '.data[] | select(.name == $auth_strategy_name) | .id')
           echo "Auth_Strategy_ID=$auth_strategy_id" >> $GITHUB_ENV
 
-      # - name: Enabling Auth Strategy
-      #   if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
-      #   run: |
-      #     response=$(curl -s -o /dev/null -w "%{http_code}" --location --request PATCH "${{ secrets.ADMIN_API_URL }}/portals/$DEV_PORTAL_ID/product-versions/$API_Product_Version_ID" \
-      #       --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
-      #       --header 'Content-Type: application/json' \
-      #       --data '{
-      #           "application_registration_enabled": true,
-      #           "auth_strategy_ids": [
-      #             "${{ env.Auth_Strategy_ID }}"
-      #           ],
-      #           "auto_approve_registration": true
-      #         }')
-
-      #     if [ $response -ne 201 ]; then
-      #       echo "Failed to enable Auth Strategy. Deleting the API product version..."
-      #       curl --request DELETE \
-      #         --url ${{ secrets.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID \
-      #         --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}'
-      #       exit 1
-      #     fi
       - name: Enabling Auth Strategy
         if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
         run: |
-          curl --location --request PATCH "${{ vars.ADMIN_API_URL }}/portals/$DEV_PORTAL_ID/product-versions/$API_Product_Version_ID" \
+          response=$(curl -s -o /dev/null -w "%{http_code}" --location --request PATCH "${{ secrets.ADMIN_API_URL }}/portals/$DEV_PORTAL_ID/product-versions/$API_Product_Version_ID" \
             --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
             --header 'Content-Type: application/json' \
             --data '{
@@ -270,4 +249,13 @@ jobs:
                   "${{ env.Auth_Strategy_ID }}"
                 ],
                 "auto_approve_registration": true
-              }'
+              }')
+
+          if [ "$response"!="201" -ne 201 ]; then
+            echo "Failed to enable Auth Strategy. Deleting the API product version..."
+            curl --request DELETE \
+              --url ${{ secrets.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$API_Product_Version_ID \
+              --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}'
+            exit 1
+          fi
+      
