update the workflow

diff --git a/.github/workflows/konnect-gateway-deployment.yml b/.github/workflows/konnect-gateway-deployment.yml
--- a/.github/workflows/konnect-gateway-deployment.yml
+++ b/.github/workflows/konnect-gateway-deployment.yml
@@ -77,9 +77,7 @@ jobs:
           KONNECT_TOKEN: ${{ secrets.KONNECT_TOKEN }}
           CP_NAME: ${{ secrets.CP_NAME }}
 
-  publish-customer-api-to-portal:
-    name: Publish OAS to dev portal
-    needs: deploy_to_konnect
+  publishAPI:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Code
@@ -115,7 +113,7 @@ jobs:
                 "labels": {}
               }'
           fi 
-      
+
       - name: Get API product ID
         run: |
           api_product_name="${{ vars.API_PRODUCT_NAME }}"
@@ -190,8 +188,39 @@ jobs:
             | jq -r --arg gateway_service_name "$gateway_service_name" '.data[] | select(.name == $gateway_service_name) | .id')
           echo "Service_ID=$service_id" >> $GITHUB_ENV
 
-      - name: Link service to the product version
+      - name: Fetch Product Version ID using Service ID
         if: env.API_PRODUCT_ALREADY_EXISTS == 'false'
+        run: |
+          service_id="${{ env.Service_ID }}"
+
+          response=$(curl --request GET \
+            --url "${{ secrets.ADMIN_API_URL }}/api-products" \
+            --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}')
+
+          product_version_id=$(echo "$response" | jq -r --arg service_id "$service_id" '.data[] | select(.gateway_service.id == $service_id) | .id // empty')
+
+          if [ -z "$product_version_id" ]; then
+            echo "Error: Product Version ID not found for the given service ID."
+            exit 1
+          fi
+
+          echo "API_Product_Version_ID=$product_version_id" >> $GITHUB_ENV
+
+          # Check if product_version_id is empty (not linked) and set a flag in the environment
+          if [ -z "$product_version_id" ]; then
+            echo "SERVICE_NOT_LINKED=true" >> $GITHUB_ENV
+          else
+            echo "Unlinking service from product version..."
+            curl --location --request PATCH "${{ secrets.ADMIN_API_URL }}/api-products/$API_PRODUCT_ID/product-versions/$product_version_id" \
+              --header 'Authorization: ${{ secrets.KONNECT_TOKEN }}' \
+              --header 'Content-Type: application/json' \
+              --data '{
+                "gateway_service": null
+              }'
+          fi
+
+      - name: Link service to the product version
+        if: env.API_PRODUCT_ALREADY_EXISTS == 'false' && env.SERVICE_NOT_LINKED != 'true'
         run: |
           echo "API PRODUCT ID: $API_PRODUCT_ID"
           echo "Control Plane ID: $Control_Plane_ID"
@@ -255,6 +284,4 @@ jobs:
             curl --request DELETE \
               --url "${{ secrets.ADMIN_API_URL }}/api-products/${{ env.API_PRODUCT_ID }}/product-versions/${{ env.API_Product_Version_ID }}" \
               --header "Authorization: Bearer ${{ secrets.KONNECT_TOKEN }}"
-          fi
-      
-          
+          }
